version: '3.8'
services:
    backups:
        # restart: unless-stopped
        container_name: ${COMPOSE_NAME}.${BACKUPS_IMAGE}
        image: ${COMPOSE_NAME}/${BACKUPS_IMAGE}
        build:
            context: .
            args:
                - NODE_VERSION=${NODE_VERSION}
                - SCRATCH_VERSION=${SCRATCH_VERSION}
        volumes:
            - '${MOUNT_BACKUPS}:/backups'
